import google.generativeai as genai
import os

def call_gemini_api(prompt):
  """
  Calls the Gemini API with the given prompt and returns the response.

  Args:
    prompt: The prompt for the Gemini model.

  Returns:
    str: The response generated by the Gemini model.
  """

  try:
    genai.configure(api_key=os.environ["GEMINI_API_KEY"])
    model = genai.GenerativeModel('gemini-1.5-flash')
    response = model.generate_content(prompt)
    return response.text

  except Exception as e:
    print(f"Error: {e}")
    return None

def apply_prompt_to_text(text, prompt):
  """
  Applies the given prompt to the input text using the Gemini API.

  Args:
    text: The input text.
    prompt: The prompt to apply to the text.

  Returns:
    str: The response generated by the Gemini model.
  """

  combined_prompt = f"{text}\n\n{prompt}"
  return call_gemini_api(combined_prompt)

# Example usage of apply prompt_to_text:
# text = "The man is called John."
# prompt = "What is the man's name?"
# response = apply_prompt_to_text(text, prompt)

# if response:
#   print(f"Response: {response}")