from abc import ABC, abstractmethod

class LLM(ABC):
    def __init__(self, api_key):
        """
        Initializes the LLM class with the provided API key.

        Args:
            api_key: The API key for authenticating with the LLM.
        """
        self.api_key = api_key
        self.configure_api()

    @abstractmethod
    def configure_api(self):
        """
        Configures the LLM API with the API key. This must be implemented by subclasses.
        """
        pass

    @abstractmethod
    def get_response(self, prompt):
        """
        Calls the LLM API with the given prompt and returns the response.

        Args:
            prompt: The prompt for the LLM model.

        Returns:
            str: The response generated by the LLM model.
        """
        pass